"""add conversation title

Revision ID: 2991485999c2
Revises: f6e0a2fabd0a
Create Date: 2026-07-03 11:50:25.200744

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '2991485999c2'
down_revision: Union[str, Sequence[str], None] = 'f6e0a2fabd0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'conversations',
        sa.Column(
            'title',
            sa.String(),
            nullable=False,
            server_default='New Conversation',
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversations', 'title')
    # ### end Alembic commands ###
