"""add session_audit

Revision ID: e0f8edb6d04e
Revises: 1363d9310174
Create Date: 2026-07-01 07:52:44.031093

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e0f8edb6d04e'
down_revision: Union[str, Sequence[str], None] = '1363d9310174'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('session_audit',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('request_id', sa.String(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=True),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('tenant_id', sa.Uuid(), nullable=True),
    sa.Column('event_type', sa.Enum('http_request', 'http_response', 'http_error', 'llm_call', 'tool_call', name='eventtype'), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_session_audit_event_type'), 'session_audit', ['event_type'], unique=False)
    op.create_index(op.f('ix_session_audit_request_id'), 'session_audit', ['request_id'], unique=False)
    op.create_index(op.f('ix_session_audit_session_id'), 'session_audit', ['session_id'], unique=False)
    op.create_index(op.f('ix_session_audit_tenant_id'), 'session_audit', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_session_audit_user_id'), 'session_audit', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_session_audit_user_id'), table_name='session_audit')
    op.drop_index(op.f('ix_session_audit_tenant_id'), table_name='session_audit')
    op.drop_index(op.f('ix_session_audit_session_id'), table_name='session_audit')
    op.drop_index(op.f('ix_session_audit_request_id'), table_name='session_audit')
    op.drop_index(op.f('ix_session_audit_event_type'), table_name='session_audit')
    op.drop_table('session_audit')
    # drop_table does NOT drop the enum type — do it explicitly so up->down->up works
    op.execute('DROP TYPE eventtype')
    # ### end Alembic commands ###
