"""add auth+chat tables

Revision ID: f6e0a2fabd0a
Revises: 37244ef8a920
Create Date: 2026-07-03 08:51:24.336109

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = 'f6e0a2fabd0a'
down_revision: Union[str, Sequence[str], None] = '37244ef8a920'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_keys', sa.Column('expires_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_api_keys_key_hash'), 'api_keys', ['key_hash'], unique=True)
    op.add_column('messages', sa.Column('seq', sa.BigInteger(), sa.Identity(always=False), nullable=False))
    op.create_index(op.f('ix_messages_seq'), 'messages', ['seq'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_messages_seq'), table_name='messages')
    op.drop_column('messages', 'seq')
    op.drop_index(op.f('ix_api_keys_key_hash'), table_name='api_keys')
    op.drop_column('api_keys', 'expires_at')
    # ### end Alembic commands ###
